version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb2
    environment:
      MONGO_INITDB_ROOT_USERNAME: nahim
      MONGO_INITDB_ROOT_PASSWORD: aemlpX43elqeuWDB
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  flightbooking:
    build: .
    command: node dist/main.js
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CLEAN_NEST_MONGO_CONNECTION_STRING=mongodb://nahim:aemlpX43elqeuWDB@mongodb2:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      - AWS_REGION=us-east-1
      - ACCESS_KEY_ID=AKIASZCTJFEFUAFCOP76
      - SECRET_ACCESS_KEY=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
      - TEST_QUEUE=flights_queue
      - TEST_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/191300708619/flights_queue
volumes:
  mongodb_data_container:
  flightbooking: